#!/bin/sh
set -o errexit
g++ -fuse-ld=lld -rdynamic -Wl,--unresolved-symbols=ignore-in-shared-libs -Wl,-rpath='${ORIGIN}' -Wl,-rpath-link='${ORIGIN}' -Wl,-rpath='${ORIGIN}'/../../bin/Linux -Wl,--as-needed -Wl,--hash-style=gnu -Wl,--build-id -o /home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a -Wl,@"/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkDire/Test.a.rsp" -Wl, -lrt -lm
"/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/Configuration/../../../bin/Linux/DumpSyms" -c -o "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a" "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a.pysm"
"/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/Configuration/../../../bin/Linux/BreakpadEncoder" "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a.pysm" "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.sym" 
"/usr/bin/objcopy" --strip-all "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a" "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a_nodebug"
"/usr/bin/objcopy" --only-keep-debug "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a" "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.debug"
"/usr/bin/objcopy" --add-gnu-debuglink="/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.debug" "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a_nodebug" "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a.temp" 
mv "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a.temp" "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.a"
chmod 644 "/home/ethanboi/Desktop/Git/Ethanboilol/Relight-Engine/Programs/RelightBuildTool/BuildTest/LinkOutput/Test.debug"
